In [2]:
import numpy as np
import sympy 
from sympy import symbols, Matrix

# Farmer's Field!

### Four equal plots enclosed in separate greenhouses. Four seedlings planted in each greenhouse, meaning there are 16 total plants. Plants are dried and weighed, resulting masses are given in a vector $\vec{d_i} = [i=1, ... , 16]$

### A model of the form $d_i = \mu + \beta_{1} \Delta_{CO2, i} + \beta_{2} \Delta_{H2O,i} + \beta_{3} \Delta_{CO2,i} \Delta_{H2O,i} + e_i $ 

where $\Delta_{CO2,i} = 0$ if A and $\Delta_{CO2,i} = 1$ if B

$\Delta_{H2O,i} = 0$ if a and $\Delta_{H2O,i} = 1$ if b

### Express the above model in matrix form such that $\vec{d} = \matrix{A}\vec{\beta} + \vec{e}$ and write down matrix $\matrix{A}$ and $\vec{\beta}$

We know that $\vec{d}$ is a column vector with 16x1 (16 rows one column). Therefore $\vec{e}$ must also be a column vector with dimensions 16x1.

When matrix$\matrix{A} $ multiplied with $\vec{\beta}$ the result must also give a vector with dimensions 16x1.

Therefore, $\matrix{A}$ must be a matrix with dimensions 16x4. While $\vec{\beta}$ must be a vector with dimensions 4x1.

Let's say i = 1,2,3,4 corresponds to plants in the Aa plot. i = 5,6,7,8 corresponds to plants in the Ab plot. i = 9, 10, 11, 12 corresponds to plants in the Ba plot. and i = 13, 14, 15, 16 corresponds to plants in the Bb plot. 

Then, A will be represented as the following matrix:




$ 
\matrix{A} = \begin{bmatrix}
1 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 \\
1 & 0 & 1 & 0 \\
1 & 0 & 1 & 0 \\
1 & 0 & 1 & 0 \\
1 & 0 & 1 & 0 \\
1 & 1 & 0 & 0 \\
1 & 1 & 0 & 0 \\
1 & 1 & 0 & 0 \\
1 & 1 & 0 & 0 \\
1 & 1 & 1 & 1 \\
1 & 1 & 1 & 1 \\
1 & 1 & 1 & 1 \\
1 & 1 & 1 & 1 \\
\end{bmatrix}
\hspace{6em} 
\vec{\beta} = \begin{bmatrix}
1 \\
\beta_{1} \\
\beta_{2} \\
\beta_{3} \\
\end{bmatrix}
$

### Find the matrix equal to the product $\matrix{A'}\matrix{A}$

A is a 16x4 matrix, A' is a 4x16 matrix. 


Therefore, A' times A should give a 4x4 matrix

In [3]:
A = np.array([
    [1, 0, 0, 0],
    [1, 0, 0, 0],
    [1, 0, 0, 0],
    [1, 0, 0, 0],
    [1, 0, 1, 0],
    [1, 0, 1, 0],
    [1, 0, 1, 0],
    [1, 0, 1, 0],
    [1, 1, 0, 0],
    [1, 1, 0, 0],
    [1, 1, 0, 0],
    [1, 1, 0, 0],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
])

A_prime = np.transpose(A)

In [4]:
AA = A_prime @ A
print(AA)

[[16  8  8  4]
 [ 8  8  4  4]
 [ 8  4  8  4]
 [ 4  4  4  4]]


### Cool! We see that $\matrix{A'} \cdot \matrix{A} $ gives a 4x4 matrix. 
$\matrix{A'} \cdot \matrix{A} = 
\begin{bmatrix}
16 & 8 & 8 & 4 \\
8 & 8 & 4 & 4 \\
8 & 4 & 8 & 4 \\
4 & 4 & 4 & 4 \\
\end{bmatrix}
$

### Write the explicit expressions for $\matrix{A'} \cdot \vec{d}$

Where $\vec{d} = \matrix{A} \vec{\beta} + \vec{e}$

We know $\matrix{A}$ and $\vec{\beta}$ and can choose some values for $\vec{e}$

$\matrix{A'} \cdot \vec{d} = 
\begin{bmatrix}
16 & 8 & 8 & 4 \\
8 & 8 & 4 & 4 \\
8 & 4 & 8 & 4 \\
4 & 4 & 4 & 4 \\
\end{bmatrix}
\cdot \begin{bmatrix}
1 \\
\beta_{1} \\
\beta_{2} \\
\beta_{3} \\
\end{bmatrix}
 + \begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 \\
\end{bmatrix} 
\cdot \vec{e}
$

where $\vec{e} = \begin{bmatrix}
e_1 \\
e_2 \\
e_3 \\
e_4 \\
e_5 \\
e_6 \\
e_7 \\
e_8 \\
e_9 \\
e_{10} \\
e_{11} \\
e_{12} \\
e_{13} \\
e_{14} \\
e_{15} \\
e_{16} \\
\end{bmatrix}
$



In [6]:
e1, e2, e3, e4, e5, e6, e7, e8, e9 = symbols('e1 e2 e3 e4 e5 e6 e7 e8 e9')
e10, e11, e12, e13, e14, e15, e16 = symbols('e10 e11 e12 e13 e14 e15 e16')
b1, b2, b3 = symbols('b1, b2, b3')

e = np.array([e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16])
beta = np.array([1, b1, b2, b3])

Aprime_d = AA @ beta 

$\matrix{A'} \cdot\vec{d}=
\begin{bmatrix}
8*b1 + 8*b2 + 4*b3 + e1 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + 16 \\
8*b1 + 4*b2 + 4*b3 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e9 + 8\\
4*b1 + 8*b2 + 4*b3 + e13 + e14 + e15 + e16 + e5 + e6 + e7 + e8 + 8 \\
4*b1 + 4*b2 + 4*b3 + e13 + e14 + e15 + e16 + 4 \\
\end{bmatrix}$

### We can see that we get a 4x1 matrix or a column vector with four rows as expected!